on:
    pull_request:
        branches: [main]
        paths: 
            - 'sudoku-vue/**'

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 24
            - name: Install dependencies
              run: |
                cd sudoku-vue
                npm install
            - name: Build project
              run: |
                cd sudoku-vue
                npm run lint:oxlint
                npm run format
                npm run build
            - name: Run tests
              run: |
                cd sudoku-vue
                npm run test:unit